# Generated by Django 5.0.4 on 2024-04-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_mastery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('full_name', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('city', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Пол', 'Мужской'), ('Пол', 'Женский')], max_length=255)),
            ],
        ),
    ]
