# Generated by Django 5.0.6 on 2024-05-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_mastery', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('image', models.ImageField(upload_to='')),
                ('full_name', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('city', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Пол', 'Мужской'), ('Пол', 'Женский')], max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
