# Generated by Django 5.0.6 on 2024-05-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_mastery', '0003_users_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
