# Generated by Django 5.0.6 on 2024-05-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_mastery', '0004_alter_users_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(choices=[('Пол', 'Мужской'), ('Пол', 'Женский')], max_length=255, null=True),
        ),
    ]
